version: '3'
services:
  flask:
    build: .
    container_name: shbr
    image: {{ env.BACKEND_IMAGE }}
    environment:
      - PYTHONUNBUFFERED=True
    restart: always
    volumes:
      - ./service:/service
    ports:
      - "80:80"
    command: ls -la
