version: '3'
services:
  flask:
    build: .
    container_name: {{ env.BACKEND_IMAGE }}
    environment:
      - PYTHONUNBUFFERED=True
    restart: always
    volumes:
      - ./service:/service
    ports:
      - "80:80"
    command: gunicorn --workers=12 --threads=6 --bind 0.0.0.0:80 application:app
