version: '3'
services:
  flask:
    container_name: shbr
    image: {{ env.BACKEND_IMAGE }}
    environment:
      - PYTHONUNBUFFERED=True
    volumes:
      - ~/data:/app/service/db
    restart: always
    ports:
      - "80:80"
